QUESTIONS = {
  "work_and_career": [
    "What's one work-related skill you'd like to develop, and why?",
    "When you think of the legacy you want to leave, does your current job contribute to that vision?",
    "On a scale of 1 to 10, how valued do you feel at work?",
    "What's a recent disagreement or conflict you had in the workplace? How did you handle it?",
    "Explain your job to a 3 year old.",
    "How do you balance work and personal life?",
    "How much of your decision to stay in your current job is influenced by comfort and fear versus ambition and fulfillment?",
    "What's the most challenging ethical dilemma you've faced in your career?",
    "What trends do you foresee in your industry in the next five years?",
    "What career decisions have you made based on fear? What decisions have been based on confidence?",
    "What's a goal or project you've made progress on?",
    "What was a pivotal moment in your career that led you to where you are now?",
    "What were some of my most challenging learning moments in your career, and what made them so?",
    "What legacy do you hope to leave as a result of your professional work?",
    "How do you contribute to a positive work environment or culture?",
    "Have any failures played a significant role in your your career development?",
    "What's your go-to productivity hack?",
    "What do you feel like you’re really good at?",
    "How do you stay productive and motivated when working from home?",
    "What's a fun project you've worked on recently?",
    "How do you reconcile the need for financial stability with the desire to pursue a passion that might be less lucrative?",
    "What's the most enjoyable project you've worked on recently?",
    "Are you currently mentoring anyone, or being mentored? How is that going?",
    "How do you think your profession will change in the future, and how are you preparing for it?",
    "What was your first job, and what did it teach you?",
    "What do you consider as red flags in a potential employer or boss?",
    "What's one thing you wish you had known when you started your career?",
    "Who had the most significant impact on your career and why?",
    "What's one piece of critical feedback you've received? How did you act on it?",
    "How has your perspective on work-life balance evolved over the years, and what influences shaped this?",
    "What do you plan to learn in the coming days?",
    "Have you ever had a mentor, and what was the most important thing they taught you?",
    "What profession would you be in if you had known about it earlier?",
    "What's a significant professional challenge you overcame in the last year?",
    "What would you consider to be a 'dream job', and how close is your current job to that ideal?",
    "How do you stay updated with the latest developments in your field?",
    "How do you approach networking, and have you had any success stories?",
    "If you could try out any other profession for a day, what would it be?",
    "How has your perspective on your career changed over time?",
    "What would make you feel like \"you made it\"?",
    "What’s your best tip for staying focused and productive?",
    "What areas of personal development do you feel you need to focus on to to achieve further professional success?",
    "What do you consider as red flags in a potential employee or coworker?",
    "How do you prioritize your tasks when everything seems urgent?",
    "Have you attended any interesting work-related seminars or workshops lately?",
    "What's a professional setback or shortfall you recently experienced, and how has it influenced you?",
    "How do you describe your current job to someone who's not in your industry?",
    "How well do you feel your work aligns with your purpose or identity?",
    "In what ways do you mentor or support others in your field?",
    "How has your industry changed since you started your career?",
    "Have you ever had to negotiate salary or a promotion? What's your strategy?",
    "How do you measure the impact of your work on society?",
    "Does your current job challenge you to grow in the ways you truly want? If not, what’s missing?",
    "What’s your take on the common career advice to \"follow your passion\"?",
    "If you could have a superpower that helps you in your current job, what would it be?",
    "What skills or passions are you not currently utilizing in your job?",
    "Have societal or familial expectations ever led you to a career decision that you wouldn't have made on your own? How do you feel about that decision now?",
    "What tools or apps do you find indispensable for your work?",
    "Would the best version of yourself be in your current job? If not, what keeps you there?",
    "What's your least favorite part of your job and why?",
    "What’s your strategy for professional growth?",
    "What's the most significant risk you've taken in your career, and how did it turn out?",
    "Thinking about your current #1 goal, what makes you optimistic you'll achieve it?",
    "What's a funny or embarrassing moment you’ve had at work?",
    "Looking back, what's one decision you made that was a leap of faith? How did it shape where you are today?",
    "Where do you see yourself professionally a year from now?",
    "What would people be surprised to learn you spend a lot of time on at work?",
    "How would you describe your approach to your career so far?",
    "What's the best career advice you've ever received?",
    "Have you ever made a dramatic career shift, and what drove that decision?",
    "What’s one of your earliest memories of earning money?",
    "What's a skill you use at work that you also use in your personal life?",
    "What's a book or podcast you'd recommend that’s related to your career?",
    "What are your biggest goals between now and the next issue of our MailPal?",
    "What is one action that would make today a success?",
    "How can you better help others succeed, especially those who often go unnoticed?",
    "Do you feel challenged enough at work?",
    "What's the most important lesson you've learned about leadership?",
    "What professional accomplishment are you most proud of and why?",
    "Have you picked up any new skills at your job this year?",
    "What's a common myth about your profession that you can debunk?"
  ],
  "worldview_and_life": [
    "If you could intervene during any historic event, changing history, what would it be? How would things unfold differently?",
    "If you had the power to completely solve one social or political issue affecting the world today, which would you choose?",
    "What do people think is hard but actually isnt?",
    "What makes you optimistic about the future?",
    "You're offered vast wealth, extraordinary intellect, renowned fame, or stunning looks. Which do you choose?",
    "Who is your favorite philosopher or thinker, and what influence have they had on you?",
    "What is one your core principles in life that is guiding you at this time?",
    "What is the most ordinary-seeming thing that you find fascinating?",
    "You can guarantee that your child will have a deep understanding of one event in history. Which event do you choose and why?",
    "What do you think is the best place or way to meet a signifcant other?",
    "What's the best outcome of a serendipitous event you've experienced in your life?",
    "What public figure has had greatest impact on your personal life philosophy?",
    "Are human desires endless, and can a society exist without wanting more?",
    "If you had the power to completely eradicate one disease, which would you choose to eliminate?",
    "What's an unconventional piece of advice that has had a significant impact on your life?",
    "When have you felt the most connected to something greater than yourself, and what were the circumstances?",
    "What is something you've become increasingly interested in the more you've learned about it over time?",
    "Think of your biggest regret. If you could go back in time and make a decision to keep it from happening, would you?",
    "What's something other people commonly do that you avoid, and are proud of doing so?",
    "Is there anything you think the previous generation did better than your generation?",
    "Is there anything you think your generation does better than the next generation?",
    "What is something you're coming to realize?",
    "If your life was a story, what chapter would you currently be in, and what would its title be?",
    "What embarrassing memory will forever be seared in your memory?",
    "Do you believe in second chances?",
    "What's one thing you would change that's commonly taught to children today?",
    "After death, you can roam the universe and observe anything you want for all eternity, but never interact with anyone or anything. Or, you can cease to exist. Which would you choose?",
    "What's something you're absolutely convinced is going to happen in the future?",
    "If you could change one thing about your childhood, what would it be?",
    "What's the worst advice you've ever been given?",
    "Can you share a personal tradition that holds deep meaning for you, and explain its origin?",
    "What is something you've done that you recommend everyone do before they die?",
    "Have you ever turned down an opportunity, then came to later regret that decision?",
    "Who do you wish was still alive? Could be someone you've met, never met, anyone.",
    "What aspects of how you were raised do you want to continue on to future generations? What aspects do you want to be sure not to repeat?",
    "What does 'living authentically' mean to you, and how do you practice it in your daily life?",
    "If you could telepathically say something that all 8+ billion people on Earth could hear at once, what would it be?",
    "If you could know for certain the answer to any question, what would that question be?",
    "What principle do you hold that you would never compromise on, even under pressure?",
    "What is the single most critical issue you would want your child to be passionate about addressing in their lifetime?",
    "How has your definition of happiness changed as you've gotten older?",
    "Have you ever desired or longed for something, but once you got it, discovered it was overrated or that you no longer wanted it?",
    "What's a common piece of advice you disagree with, and why?",
    "What's your philosophy in life?",
    "What's something you're you proud of, but never have an excuse to talk about?",
    "What do you know isn't real, but really wish it existed?",
    "If you could choose one experience from your life that your child could also have, what would it be?",
    "What was the scariest moment of your life thus far?",
    "What subject or course do you wish they had offered in school?",
    "What do you think all happy people have in common?",
    "What person in your life do you most admire?",
    "What is the smallest thing for which you are grateful?",
    "What do you think happens after we die, if anything?",
    "What advice do you wish you'd received earlier?",
    "Is there anything you think the next generation will do better than your generation?",
    "What's something very strange that happened to you?",
    "Spiritually, do you believe in something bigger than yourself? What inspired this belief?",
    "What is your why? What gets you up in the morning?",
    "Which is more important, nature or nurture?",
    "What's the best advice you've ever given someone?",
    "What advice would you give to your teenage self?",
    "What's a current trend you find concerning?",
    "If you could instantly bankrupt any person, company, country, or organization, who would it be?",
    "What's the most useful thing you've ever been taught in school?",
    "If you could promote one value or ethic in the world, what would it be and why do you think it's vital?",
    "What's your favorite quote and why?",
    "You can only guarantee your child learns one life principle. What do you teach them?",
    "If you could have witnessed one event from your family history, what would it be?",
    "What is something that is important to you that you never really talk about?",
    "How do you reconcile the pursuit of your personal goals with the need to contribute to the community?",
    "Think of the best teacher you've ever had. What did they teach, and what made them so special?",
    "What's the most likely cause for the end of humanity, and how do we stop it?",
    "What did you learn about the concept of love from your parents? Is there anything you want to keep, or anything you want to let go?",
    "Imagine you could instill one habit in your child that they would carry for life. What habit would you choose and why?",
    "When was the last time you experienced stillness and wonder?",
    "What's an unpopular or controversial opinion that you hold?",
    "You can go back in time and experience any historical event. Where do you go, and when?",
    "Which societal norm would you like to see ended, and why? What changes would you propose?",
    "What do you believe is the most significant factor in shaping one's destiny, and how much control does one have over it?",
    "Who in your life do feel is receptive to receiving feedback?",
    "In what ways do you think hardship can contribute to personal growth?",
    "If you could change anything about the way you were raised, what would it be?",
    "Is there anything you think your generation does better than the previous generation?",
    "Have you ever had an epiphany? What was it about, and what sparked the realization?",
    "What one thing (something you made, something you did, something you contributed to) would you like to be remembered by?",
    "What do you think is the most important quality of human civiliation for its continued survival?",
    "Who in your life would you trust with your deepest secret?",
    "What character trait instantly makes you respect someone?",
    "What is the most trivial thing about which you have a strong opinion?",
    "A highly advanced alien species has arrived on Earth, and you are selected as the spokesperson to represent humanity. You have one sentence to communicate your most important message. What do you say?",
    "What's the most useless thing you've ever been taught in school?",
    "You can impart one understanding about human relationships to your child. What insight do you choose to share?",
    "Who in life has inspired you the most?"
  ],
  "self_reflection": [
    "What's something you strongly believed in your childhood that you no longer feel sure about?",
    "If you only had one year left to live, what would you do?",
    "If you could go back and relive one day in your life without changing anything about it, which day would you choose?",
    "What's one way in which you're completely different from yourself 10 years ago?",
    "What would you title your memoir?",
    "What fact about yourself took you the longest to understand or accept?",
    "Does anybody beside yourself know your deepest secret? Do you ever intend to tell anyone?",
    "What's something you used to be ashamed of but have come to embrace?",
    "What was the last fear you overcame and how?",
    "What's your favorite personality or character trait about yourself?",
    "What's something from your childhood that you think no one else could relate to?",
    "What's something people often incorrectly assume about you?",
    "Do you love yourself? What does that look like?",
    "If you could only use five words, how would you describe yourself?",
    "Which childhood book or story influenced you the most?",
    "What's one thing about you that hasn't changed in the last 10 years?",
    "When was the last time you cried and why?",
    "How would you summarize your last 12 months in one sentence?",
    "What's a habit you picked up as a child that you wish you hadn't?",
    "When do you feel most helpful to others?",
    "Are you settling for less than what you are worth? If so, why?",
    "What's a fear you've faced and overcome?",
    "If you could ask your future self one thing, what would it be?",
    "What inaction or missed opportunity do you regret?",
    "Who has had the most positive impact on your life?",
    "How would you describe your relationship with yourself in a single word?",
    "What is something you never thought you'd be able to do, until you actually did it?",
    "What lesson have you had to learn again and again?",
    "What title would you give to the current phase of your life?",
    "What are you most afraid of about yourself?",
    "How do you approach your overall wellness?",
    "Do you have any biases you're aware of?",
    "What is something other people admire about you?",
    "Is there anything important you've been putting off? If so, why?",
    "Have you learned the lesson of forgiveness? Why or why not?",
    "Do you have an inner monologue? Do you think your thoughts in words or concepts?",
    "What practice or habit (if anything) best supports your mental health/well-being?",
    "What is your biggest accomplishment outside of academia and work?",
    "What's something that you wish was easier for you?",
    "Are you currently holding a grudge against anyone?",
    "What do you think is your biggest strength and your biggest weakness?",
    "What past compromises do you refuse to make now?",
    "How can you take better care of yourself? How will you make that happen?",
    "How do you think you'll be completely different from yourself 10 years from now?",
    "What area in your life are you looking to improve?",
    "What bad habits would you like to get rid of? What steps do you need to take to make that happen?",
    "What are your best habits? How did you develop them?",
    "What was your \"rock bottom\"? How did it happen, and how did you get out of it?",
    "What do you take for granted?",
    "What's the best lesson you've learned from a difficult situation?",
    "What is something that's easy for you but seems difficult for most other people?",
    "What do you think will still be the same about you 10 years from now?",
    "When do you feel most like yourself?",
    "What does your ideal/dream life look like?",
    "What is the quality you admire the most in the person you dislike the most?",
    "What word describes your essence the best?",
    "Do you think you fit a particular stereotype? Which one, and why?",
    "What single event or decision do you think most affected the rest of your life? Was there a turning point in your life?",
    "What is the hardest way you’ve learned an important lesson?",
    "What is the dumbest but most innocent thing you believed as a child?",
    "What's something you wish people asked you about more often?",
    "What do you think is the most misunderstood aspect of your personality by others?",
    "What would you most like to become famous for?",
    "Has your gut feeling or intuition about someone or something ever been wrong?",
    "What's something people are surprised to learn about you?",
    "The world needs more of my...",
    "What is an irrational fear you have?",
    "What talent of yours do you consider to be inherent, like an advantage you were born with?",
    "Are there any inner thoughts you have that bother you?",
    "What's the most important life lesson you've learned in the last 10 years?",
    "How would you summarize your life so far in one sentence?",
    "How authentically do you feel you represent yourself to others?",
    "What stopped you from following, or encouraged you to follow, your childhood passion?",
    "You just inherited $10,000,000. How does your life change tomorrow?",
    "What activity absorbs you completely and makes you lose track of time?",
    "What's something you'd like to do, but have a hard time acting on?",
    "Is there any aspect of your identity you sometimes feel you must suppress or amplify in certain social settings?",
    "What are 3 things you love about yourself?",
    "What trait do you admire in others but don't possess yourself?",
    "What are you most jealous of about others?",
    "If you could alter one decision you made in your early 20s, what would it be?",
    "What kind of person do you want to be?",
    "What's the one thing you would like to change about yourself?",
    "How do you prioritize your goals and desires in life?",
    "What's your biggest dream?",
    "What life event did you learn the most from? Would you change it?",
    "What is one thing you're tired of explaining to people?",
    "Is there something you wish everybody knew about you without you having to tell them?",
    "If you had one minute left to live, what would you do?",
    "Are you waiting on someone or something to progress in an aspect of your life?"
  ],
  "random_and_fun": [
    "If you had to get a tail, what tail would you want and what would you use it for?",
    "If you could use a time machine, would you rather have one that only goes back in time or only goes forward?",
    "Who here is is most likely to join the secret service?",
    "If you could choose one superpower, but it had to be extremely specific and unusual, what would it be?",
    "What does your dream home look like?",
    "What's your favorite toy?",
    "If you were a dictator of a small country, what crazy dictator things would you do?",
    "If you had to skip on meal every day for the rest of your life, which meal would it be?",
    "You can know when you die or how you die. Which do you choose?",
    "If your life was a genre of music, what would it be?",
    "Who here is is most likely to establish a scientific law?",
    "Where do you wish you had grown up?",
    "You're given a sidekick with any superpower of your choosing. What's their name, and what's their power?",
    "Who here is most likely to own 20 house plants and give each of them unique names?",
    "What is something you're terrible at but wish you could do well?",
    "You can stop time for 24 hours. What do you do with this opportunity?",
    "A stranger is inhabiting your body for the day. What are some tips you’d give them?",
    "Would you rather have the power to turn invisible or to read minds?",
    "If you could level up any aspect of yourself (i.e., strength, intelligence, charisma, etc.) but you had to decrease another aspect of yourself by the same amount, what aspects would you level up and sacrifice?",
    "If you could witness any event in the future, what would you choose to see?",
    "What's one rule you'd put in place if you ruled the world for a day?",
    "Do you have any conspiracy theories? If so, what are they?",
    "Who here is is most likely to eat cat food?",
    "What's something expensive you splurge on that you believe is worth the money?",
    "Who here is most likely to invent the next technology that'll save the planet?",
    "What's something that will make you smile every time?",
    "What is something you hate, that everyone else loves?",
    "If you were in a zombie apocalypse and you could only choose 3 people, would you be on your team?",
    "Which superpower would you pick to subtly make your everyday life easier?",
    "Who here is most likely to leave their inheritance to a ferret that only has a 3-year lifespan?",
    "Imagine you woke up with the ability to speak every language fluently; how would you use this power first?",
    "If you were perpetually surrounded by one aroma (asides your own, natural scent) which you and everyone around you could smell, what would it be?",
    "If you could have any author write your life story, who would you choose?",
    "You have to start a business. If you already have one, it can't be your current one. What would you name it, and what would it do?",
    "Who here is most likely to dedicate their life trying to go to another planet?",
    "What color describes your mood today?",
    "What's one of your biggest pet peeves?",
    "What are some bad things you did as a teenager?",
    "If you had 9 lives, what would you do with them?",
    "Without saying what the category is, what are your top five?",
    "What's your favorite article of clothing you own?",
    "What's a time when you were extremely underprepared for the task or situation at hand?",
    "What is the one thing you've made that you're the most proud of?",
    "What is something you love, that everyone else hates?",
    "Who here is is most likely to look almost the same years from now?",
    "If all animals were the same size, what would win in a fight?",
    "Do you have a best year of your life? A worst?",
    "Who here is is most likely to have the most children?",
    "If you could witness any event from the past, present, or future, what would it be and why?",
    "What was the best birthday gift you ever got?",
    "What's one thing you miss the most growing up as a kid?",
    "What's the most bizarre dream you've ever had?",
    "If you were reincarnated as an animal based on your personality, what animal do you think you would come back as?",
    "What's something that will never cease to make you laugh?",
    "What's an ethical dilemma that keeps you up at night?",
    "Who here is most likely become a philanthropist?",
    "If you could change one thing about yourself physically, what would you change?",
    "If you could be the CEO of any company, what company would you choose?",
    "What fictional character do you most relate to?",
    "It's \"Freaky Friday\". You wake up in someone else's body for a day. Who would you like to wake up us, and have them inhabit your body instead?",
    "If every time you snapped your fingers, you would instantly and irreversibly be transported to a random point in humanity's timeline, would you snap your fingers? If so, how often?",
    "Who here is would most likely become a CEO at a company ranked amongst the top 100 largest in the world?",
    "What's something you're embarrassed to admit you enjoy?",
    "Are you known for having a personal catchphrase, or something you say often?",
    "If you were an inanimate object, what would you be and why?",
    "If you had to give a TED Talk without any preparation, what topic would you choose?",
    "Imagine you could bring drawings to life; what’s the first thing you would draw?",
    "What song is 10/10 in your book, but no one has heard of it?",
    "If you could create a new holiday, what would it celebrate?",
    "What's a great name for a pet but a terrible name for a human?",
    "If you had the power of perfect memory recall, what’s the first memory you’d revisit?",
    "What fictional character would you most like to have as a mentor?",
    "What is the most memorable meal you've ever had? (It can be good or bad.) What made it so memorable?",
    "What is the greatest physical pain you've ever felt?",
    "Which superhero’s powers do you feel are underestimated?",
    "Who here is would most likely live the longest?",
    "A surprise package arrives at your doorstep — it's from everyone here! What's inside?",
    "What is a childhood habit or preference that you'll never outgrow?",
    "You just became a new member of the Spice Girls. What's Spice name do you create for yourself?",
    "Imagine that you can choose when and how you die. How long would you like to live, and how would you like to go?",
    "What kind of games did you play as a child?",
    "What's one thing that you wish would never happen to you?",
    "What is your most terrible memory?",
    "Did your household ever have a cooking disaster, or a meal that turned out really badly one time?",
    "You get to invent something. What is it and what does it do?",
    "Who here is is most likely to call in sick at work just to travel for a concert in another state?",
    "You can go back in time for 5 minutes. What would you do?",
    "What's the best compliment you've ever received?",
    "What scientific or technological advance blows your mind?",
    "If you could be invisible, but it would mean being permanently invisible, would you want to be this way?",
    "Who here is most likely to bring an axe to a pillow fight?",
    "What's your favorite non valuable item you'll keep to the grave?",
    "Given the choice of anyone in the world, whom would you want as a dinner guest?",
    "Who here is most likely to call in sick at work just to travel for a concert in another state?",
    "You're gifted 24 hours where you and your pet(s) are suddenly able to talk to each other. What would you want to tell them, and how would you want to spend your time with them?",
    "What movie traumatized you as a kid?",
    "If you were a teacher, what would you teach and what ages would your students be?",
    "If you could learn one secret from anyone, who would it be and what would it pertain to?",
    "Do you have an internal hunch about how you will die?",
    "If you could erase one thing or event from your memory, what would you choose?",
    "What outfit makes you feel powerful, smart, or capable?",
    "What's the weirdest food combination you actually enjoy?",
    "Who here is is most likely to read every book in a school library?",
    "Some historical figures have epithets attached to their names (e.g. Alexandar The Great, or Michael Jackson: King of Pop). What would you like yours to be?",
    "If seasons never changed, which would you most like to live in eternally?"
  ],
  "relationships": [
    "In what way do you differ most from your romantic partner? In what way are you most similar?",
    "What do you think people might envy you for?",
    "What is one commitment you've made to showing up differently in a particular relationship of yours?",
    "What's something you wish you knew earlier about being a good partner?",
    "What's a recent moment in which you're proud that you spoke up?",
    "What was your worst conflict with a partner and what happened? What'd you learn from the experience?",
    "What do you consider as red flags in a potential friendship?",
    "How do you feel about your relationship with your mother?",
    "What boundary did you recently set that has improved your relationship with someone?",
    "Who in your life always makes you laugh?",
    "What's something you admire about each person here?",
    "Are you closer to one of your parents than the other, and why?",
    "What traits in others are you attracted to?",
    "In what way do you differ most from your best friend? In what way are you most similar?",
    "In what ways are you similar to your parents? In what ways are you different?",
    "Who's life do you think you've impacted the most?",
    "What social behaviors of yours are driven by the need for safety, belonging, acceptance, or validation, rather than genuine desire?",
    "Complete this sentence: \"I wish I had someone with whom I could share ... \"",
    "When was the last time you had a difficult conversation? Who was it with, and how did it go?",
    "What behavior or trait immediately makes you like someone?",
    "What's the best relationship advice you've ever received?",
    "What is the most important quality you look for in a friend?",
    "What have you previously tolerated that you no longer allow in your life?",
    "How has your relationship with your parents changed as you've gotten older?",
    "Are there any relationships in your life that feel imbalanced? What would it look like to restore balance?",
    "If you were to suddenly inexplicably go missing, who in your life would be most likely to solve the mystery and find you?",
    "What was your relationship like with your siblings growing up? If you didn't have them, who did you spend a lot of time with?",
    "What's a recent moment in which you feel you represented yourself authentically?",
    "In three words, how would your family and friends describe you?",
    "What behavior or trait immediately makes you respect someone?",
    "What do you consider as red flags in a potential romantic relationship?",
    "What behavior or trait immediately makes you trust someone?",
    "How do you show someone you care about them?",
    "What's your ideal first date?",
    "Who do you go to for advice, and why?",
    "What or who do you have an unhealthy relationship with?",
    "What’s one family tradition you want to pass down to your kids?",
    "Who is someone that you recently issued a genuine apology, and what was it for?",
    "How do you feel about your relationship with your father?",
    "What community do you currently feel the most connected to?",
    "Is there anyone you envy? If so, whom and for what?",
    "Which relationships are you investing the most in right now?",
    "What instantly makes you think less of someone?",
    "Think of someone you're currently in conflict with. If it was the last conversation you'd ever have with them, what would you say?",
    "Which of your expectations of someone is causing hurt?",
    "What is your best advice on how to apologize?",
    "If you have siblings, how do you (or did you) quarrel with them?",
    "What crucial boundary do you need to establish with someone in your life? What's been holding you back?",
    "What's a \"red flag\" in a relationship or friendship?",
    "What are the top three qualities of your ideal partner?",
    "What behaviors will you no longer accept in your relationships?",
    "What's your favorite memory with your family?",
    "Which relationship in your life do you currently find the most challenging? What are you learning from it?",
    "What's the most important lesson a friend has taught you?",
    "What's the hardest part about maintaining relationships for you?",
    "To what degree do you modify your behavior based on who you're with? Do you think this is good or bad?",
    "Is there anyone close in your life that perceives you differently than you perceive yourself?",
    "How well do you receive feedback?",
    "What do you most need to hear right now, and from whom?",
    "Who is someone you think about a lot, that isn't thinking about you nearly as much? What do you make of this?",
    "What did you learn about yourself from your last relationship?",
    "What advice would you give about maintaining long-lasting relationships?",
    "What trait signals to you that someone is wise?",
    "What's some surprising feedback you recently received?",
    "What does love mean to you?",
    "Is there anyone in your life being impacted by your insecurities?",
    "What was your parents' relationship like?",
    "Which relationships have become more meaningful to you as of late?",
    "If you accomplished something major, who is the first person you'd tell and how do you think they'd react?",
    "Before having a conversation with someone, do you ever rehearse what you are going to say? Why",
    "Do you feel like you've found \"your people\" yet in life?",
    "What are you working on in your relationships (with friends or with a partner) right now?",
    "If you could teach someone just one thing about how to be in a good relationship, what would it be?",
    "How do you resolve conflict with the closest people in your life?",
    "What's a difficult conversation you've been meaning to have?",
    "What was your most memorable moment with your parent(s)?",
    "What first impression do you hope you make on people?",
    "What quality do you most appreciate about your partner?",
    "Is there anyone who intimidates you? Why do you think this is?"
  ],
  "icebreakers": [
    "What skill of yours are you most proud of?",
    "You will be granted supernatural ability in one of your five sense (sight, smell, taste, hearing). Which would you choose, and why?",
    "What's the most valuable lesson you've learned from a culture different from your own?",
    "What's a hobby you've always wanted to try?",
    "What does \"success\" mean to you, and how has that definition evolved over time?",
    "What character traits do you most appreciate in your teammates?",
    "If you had the power to talk to animals, which species would you chat with first?",
    "If you were a pizza topping, what would you be and why?",
    "What is your most regretful purchase?",
    "What's the most unusual food you've ever tried, and would you eat it again?",
    "What's something you're frequently complimented on?",
    "Which best describes you? An introvert or an extrovert?",
    "Can you share an instance where your first impression of someone was completely wrong?",
    "How has your perspective on the world changed in the last five years?",
    "What's one thing you've never done but feels like it's something you need to do in your lifetime?",
    "What's the most memorable dream or nightmare you've ever had?",
    "Can you share a personal goal that you haven't achieved yet and why it's important to you?",
    "What's your earliest memory?",
    "What life experience has shaped you the most, and in what way?",
    "If you could travel anywhere in the world right now, where would you go and why?",
    "What's your favorite memory in your childhood home?",
    "Can you share an unexpected goal you have for this year?",
    "If you had $1M, but couldn’t spend a penny of it on yourself, what would you spend it on?",
    "How do you find balance between your personal and professional life?",
    "If you could start your own charity, what would it focus on?",
    "What's the best advice you've ever received?",
    "What's your favorite snack?",
    "What's a memorable lesson you've learned from a mistake you've made?",
    "What's your favorite way to unwind after a busy week?",
    "Where were you born?",
    "What's a challenge you've overcome that made you a stronger person?",
    "If you could live in any movie universe for a week, which one would you pick?",
    "What was your favorite childhood toy?",
    "Is there a particular event or moment that redirected the course of your life? How did it impact you?",
    "What's a movie you can watch over and over without ever getting tired of?",
    "What's something you've achieved that you never thought possible for yourself?",
    "What's the most significant risk you've ever taken, and how did it turn out?",
    "If you could have any mythical creature as a pet, which one would you choose?",
    "What was your first job ever?",
    "What’s is one thing we don’t know about you?",
    "If you had to choose a theme song for your life, what would it be?",
    "What's a major life decision you made that you're really happy about?",
    "If you could pick a new first name for yourself, what name would you choose and why?",
    "What is the last book you read? Would you recommend it?",
    "What's a situation that tested your resilience?",
    "What's your favorite smell?",
    "What do you think is the most significant impact individuals can make in the world today?",
    "What is your favorite word and why?",
    "If you could have dinner with any person, living or deceased, who would it be and why?",
    "Is there an experience you think everyone should have at least once in their lives?",
    "What's a belief you held strongly that you changed your mind about?",
    "What is your best season of the year? Why?",
    "What's a moment in your life that felt like a crossroads?",
    "What's the quirkiest habit you have that you're willing to admit?",
    "What's something you're looking forward to in the coming months?",
    "What was your least favorite food growing up?",
    "What's the most challenging thing you're working through these days?",
    "What are people surprised to learn you're really good at?",
    "What was the sickest you ever got, as a child?",
    "What would you do if there were no internet for the next 24 hours?",
    "If you could pick up a new skill in an instant, what would it be?",
    "What's your secret talent that no one would expect you to have?",
    "Name one thing that stresses you out without fail.",
    "What's a deep question you often ask yourself?",
    "What's a surprising hobby you enjoy?"
  ],
  "check-in": [
    "Is there a quote or saying you call to mind often, intentionally or unintentionally?",
    "What indulgence do you currently spend the most money on?",
    "What's a habit you're trying to develop or break?",
    "What's a compliment you recently received?",
    "Have you tried any new foods or restaurants lately?",
    "What's a recent decision that was hard to make?",
    "What's a funny or interesting story from your week?",
    "What’s a new movie or show you've enjoyed recently?",
    "What are you addicted to lately?",
    "What are you most grateful for in your life right now?",
    "What's your most common feeling lately?",
    "What self-limiting beliefs do you currently hold?",
    "What would you like to thank yourself for right now?",
    "What is one thing you didn’t do so well recently?",
    "What are some of your recent highlights and lowlights?",
    "On a scale of 1-10, how happy are you?",
    "What's something that tends to ruin your day as of late?",
    "What battles are you fighting right now?",
    "Who has made a positive difference in your life recently?",
    "What's a new hobby or activity you've tried recently?",
    "What was the most recent thing that made you cry?",
    "What's that one thing you keep buying or doing even though you know it's unhealthy?",
    "What do you wish people would ask you more about right now?",
    "What thoughts distract you when you’re trying to get to sleep?",
    "What do you wish you had done differently in the last month?",
    "What are 3 words you'd used to describe how you currently feel?",
    "What's a goal you're working towards?",
    "What do you wish people would stop talking about right now?",
    "What is the most powerful habit, good or bad, in your life right now?",
    "What's the most fun you recently had? What did you do, and who were you with?",
    "What have you been dreaming of eating lately?",
    "Explain your current feelings in life to a 3 year old.",
    "What gives you supreme joy right now?",
    "What elements of your daily routine have become non-negotiable lately?",
    "What recent mistake taught you the most?",
    "What can you be kinder towards yourself for right now?",
    "What's a challenge you recently faced?",
    "How did you spend your most recent weekend?",
    "What's something you're looking forward to doing or experiencing?",
    "What's one thing you recently did for yourself?",
    "What’s your dream vacation right now? Why?",
    "What's a standout moment where you felt excited recently?",
    "Is there a behavior or pattern you keep falling into that hurts yourself?",
    "What’s one thing that brings you energy and joy lately?",
    "How's your family doing?",
    "What do you wish people would talk more about right now?",
    "What's the most exciting improvement you've been seeing in yourself recently?",
    "What's something you recently came across that gave you hope or inspiration?",
    "What's a deep or difficult question you've been pondering lately?",
    "What's a significant change you're considering or have made?",
    "What's currently worrying you?",
    "How can you create an environment that will naturally bring about your currently desired change?",
    "Have you been to any cool places lately?",
    "What's going well with work or school? What's not going well?",
    "How is your current health, fitness, or wellness routine going?",
    "What's something you are really into right now?",
    "What's a truth you've recently come to terms with?",
    "What's a recent personal growth moment you've experienced?",
    "Is there anything you'd like to get off your chest?",
    "What's your favorite way to relax these days?",
    "What's something you could talk about for hours right now?",
    "What's something you did recently that took courage?",
    "What have you been eating lots of lately?",
    "What's a habit you'd like to adopt, but find difficult to stick to?",
    "What's a recent decision you're glad you made?",
    "What’s something at the top of your to-do list?",
    "What compliment would you give yourself right now?",
    "What are you grateful for lately?",
    "What's one interesting thing you've been thinking about lately?",
    "If you had a magic wand, how would your life magically be better a month from now?",
    "What aspects of life are you loving most right now?",
    "How have you been lately?",
    "What's something you're interested to learn more about?",
    "What's something you've recently let go of, and how has it impacted you?",
    "Where you currently facing uncertainty or unknown, and how are you navigating it?",
    "What quality are you currently cultivating in yourself?",
    "What actions, if taken, would make you proud of yourself a month from now, regardless of the outcome?",
    "What made you happy today?",
    "Do you feel you're operating in a sustainable way?",
    "What is the most fun you have had recently?",
    "What's a great piece of advice you recently received? Who was it from?",
    "What's a new skill or knowledge you're learning right now?",
    "What’s your biggest flex in life right now?",
    "What area in your life do you feel you’re making progress? Not making progress?",
    "What kind of a day have you had so far today?",
    "What song has been on repeat for you lately? Does it have any special meaning?",
    "What’s a mantra or affirmation you resonate with right now?",
    "Who helped you recently?",
    "Think of one of your big, lofty goals. What small step could you take today towards achieving it?",
    "What's been on your mind a lot lately?",
    "What's something you recently taught yourself?",
    "What's the best purchase you recently made?",
    "What would brighten your day today?",
    "What are you most proud of right now?",
    "What did you recently fail at? What did you learn from it?",
    "Which form of self-expression has become increasingly important to you?",
    "What's something you currently doubt, conciously or subconsciously, that you can do?",
    "What’s something that made you laugh recently?",
    "What's one thing you do to distract yourself that you think you should less of?",
    "How have you stepped out of your comfort zone recently?",
    "What's an interesting conversation you recently had?",
    "Where do you feel you're improving the most?",
    "What do you find yourself fantasizing about these days?",
    "How well are you taking care of yourself lately?",
    "What's something you've been reminding yourself to think, do, or feel lately?",
    "What's something you recently learned?",
    "What's a fear or insecurity you're working through?",
    "What has surprised you recently?",
    "What's a personal value or belief you've been reflecting on?",
    "How’s your heart today?",
    "What do you have up in your browser tabs right now?",
    "What's something good that recently happened to you?",
    "Have any priorities recently shifted to the forefront of your life?",
    "If the last month were a chapter of your life, what would you title it?",
    "What was your biggest win lately?"
  ]
}

def create_questions(questions)
  questions.each do |category, questions|
    questions.each do |question|
      Question.create!(
        prompt: question,
        asked_by: "MailPals",
        category: category
      )
    end
  end
end

def up
  create_questions(QUESTIONS)
  @user = User.create!(email: "test@test.com", username: "test123", name: "Test User", verified: true, password: "Secret1*3*5*", password_confirmation: "Secret1*3*5*")
  @club = Club.create!(
      title: "My Club",
      description: "My Club Description",
      active: true,
      default_number_questions: 1,
      delivery_time: 1,
      delivery_frequency: 1,
      delivery_day: 1,
      invite_code: '123456',
  )
  @member = Member.create!(
      display_name: "First Member",
      user: @user,
      club: @club,
      role: "owner",
      activated_at: Time.current
  )
  @issue = @club.issues.first
  @answer = Answer.create!(issue_question: @issue.issue_questions.first, member: @member, content: "42")
end

if Rails.env.development?
  create_questions(QUESTIONS) unless Question.count > 0
  
  # Create test users
  users = [
    {
      email: 'alice@example.com',
      username: 'alice123',
      name: 'Alice Smith',
      verified: true,
      password: 'Password123!',
      password_confirmation: 'Password123!'
    },
    {
      email: 'bob@example.com',
      username: 'bob456',
      name: 'Bob Johnson',
      verified: true,
      password: 'Password123!',
      password_confirmation: 'Password123!'
    },
    {
      email: 'carol@example.com',
      username: 'carol789',
      name: 'Carol Williams',
      verified: false,
      password: 'Password123!',
      password_confirmation: 'Password123!'
    },
    {
      email: 'dave@example.com',
      username: 'dave101',
      name: 'Dave Brown',
      verified: true,
      password: 'Password123!',
      password_confirmation: 'Password123!'
    }
  ]

  # Create users if they don't exist and store them for reference
  created_users = users.each_with_object({}) do |user_attrs, memo|
    memo[user_attrs[:username]] = User.find_or_create_by!(email: user_attrs[:email]) do |user|
      user.assign_attributes(user_attrs)
    end
  end

  # Create Book Lovers club if it doesn't exist
  book_lovers = Club.find_or_create_by!(title: 'Book Lovers') do |club|
    club.description = 'A club for passionate readers to discuss their favorite books'
    club.active = true
    club.default_number_questions = 2
    club.delivery_time = 9
    club.delivery_frequency = 1
    club.delivery_day = 1
    club.invite_code = 'BOOKS123'
  end

  # Create memberships with different roles
  {
    'alice123' => 'owner',
    'bob456' => 'member',
    'carol789' => 'member',
    'dave101' => 'member'
  }.each do |username, role|
    Member.find_or_create_by!(
      user: created_users[username],
      club: book_lovers
    ) do |member|
      member.display_name = created_users[username].name
      member.role = role
      member.activated_at = Time.current
    end
  end
 
  # Create a past issue
  past_issue = Issue.find_or_create_by!(
    club: book_lovers,
    open_at: 2.weeks.ago,
    deliver_at: 2.weeks.ago,
    sent_at: 2.weeks.ago,
    sections: ["questions"]
  )

  # Generate questions for the issue
  past_issue.generate_questions(1)

  # Create answers for each member
  members = Member.where(club: book_lovers)
  issue_question = past_issue.issue_questions.first

  members.each do |member|
    Answer.find_or_create_by!(
      issue_question: issue_question,
      member: member,
      content: "This is #{member.display_name}'s answer to the book club question."
    )
  end
end

if Rails.env.production?
  create_questions(QUESTIONS) unless Question.count > 0
end
